### ISSUE TITLE
analyzer fails on selector with trailing comma

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/css-analyzer#127]
Example CSS:

```css
body.page .article-divider-ns::after, {
  top: 57px;
}
```

It breaks on calculating specificity on the selector with the trailing comma.
