### ISSUE TITLE
Report Duplications

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/css-analyzer#136]
Duplications in CSS may appear in many forms, so first we'll need to decide how to count them. My preference would be like this:

```css
/* 1 duplicate (property and value are an exact match) */
.selector1 {
  color: red;
}
.selector2 {
  color: red;
}

/* No duplicate (because of !important, the value is not an exact match */
.selector3 {
  color: red;
}
.selector4 {
  color: red !important;
}

/* Duplicate (because of !important for both values */
.selector5 {
  color: red !important;
}
.selector6 {
  color: red !important;
}

/* 1 duplicate, because the selectorList for both rules is the same */
.selector7,
.selector8 {
  color: blue;
}
.selector7,
.selector8 {
  font-size: normal;
}

/* 1 duplicate, because `.selector9` appears in the selectorList of both rules */
.selector9,
.selector10 {
  color: blue;
}
.selector9 {
  color: red;
}

/* 1 duplicate, because `.selector11` appears as an ideintifier in `.selector12` */
.selector11 {
  color: blue;
}
.selector12 > .selector11 {
  color: green;
}
```
