### ISSUE TITLE
Analyzer breaks when parsing @font-face

### ISSUE THREAD

**Issue by maliMirkec** [projectwallace/css-analyzer#211]
This is the code that makes the analyzer break:

```css
@font-face{font-family:fontawesome;font-display:swap}
```

Here's the error:

![image](https://user-images.githubusercontent.com/2345786/151942999-db4a8b6f-0347-4d3c-8aee-e9ccef081f5e.png)

Is there a way to fix this without removing the `@font-face` code?
