### ISSUE TITLE
Analyzer breaks on encoding issue

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/css-analyzer#307]
```css
@font-face {
        font-family: &#x27;Graphik&#x27;;
        font-stretch: normal;
        font-style: normal;
        font-weight: 400;
        font-display: swap;
        src: url(&#x27;https://www.vistaprint.nl/swan/v1/fonts/graphic_regular2.7c96db81b23a97fd67cbeb7e7efad583.woff2&#x27;) format(&#x27;woff2&#x27;),
          url(&#x27;https://www.vistaprint.nl/swan/v1/fonts/graphic_regular.e694f50e9c3a4ee999da756a90b0e872.woff&#x27;) format(&#x27;woff&#x27;);
      }

        @font-face {
          font-family: &#x27;Graphik&#x27;;
          font-stretch: normal;
          font-style: normal;
          font-weight: 700;
          font-display: swap;
          src: url(&#x27;https://www.vistaprint.nl/swan/v1/fonts/graphic_medium2.3829398551b96ac319a48122465462c2.woff2&#x27;) format(&#x27;woff2&#x27;),
            url(&#x27;https://www.vistaprint.nl/swan/v1/fonts/graphic_medium.1e5761591bb4bdd7e1d6ef96bb7cef90.woff&#x27;) format(&#x27;woff&#x27;);
        }
```

At-rule (font-face) analysis breaks because of the HTML entities (`&#x27;`), but should just skip the whole at-rule in that case, or maybe just the descriptor.

--- 

The fact that this is probably an issue with the framework that renders the site does not mean the analyzer should fail on it because of TypeErrors.
