### ISSUE TITLE
Incorrect unit  analysis on `quotes` property

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/css-analyzer#325]
```css
q{quotes:2 1C 2 1D 2 18 2 19}
```

Source: syntax.fm

`C` and `D` are reported as units, which they aren't.
