### ISSUE TITLE
Incorrect font-size

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/css-analyzer#336]
From cssday.nl

```css
body {
  font: 100% Source Code Pro, Inconsolata, Menlo, monospace;
}
```

Expected: `100%`
Actual: `Code`
