### ISSUE TITLE
🏘️ Analyze @property usage

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/css-analyzer#339]
Seeing some noise around the use of `@property`, so it's probably nice to audit your properties.

Some examples by @argyleink:

https://nerdy.dev/cant-break-this-design-system

```css
@property --focal-size {
  syntax: '<length-percentage>';
  initial-value: 100%;
  inherits: false;
}

@property --hue {
  syntax: '<angle>';
  initial-value: .5turn;
  inherits: false;
}

@property --surface {
  syntax: '<color>';
  initial-value: #333;
  inherits: true;
}

@property --surface-over {
  syntax: '<color>';
  initial-value: #444;
  inherits: true;
}

@property --surface-under {
  syntax: '<color>';
  initial-value: #222;
  inherits: true;
}

```

CanIUse https://caniuse.com/mdn-css_at-rules_property
