### ISSUE TITLE
Count (shorthand) overrides

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/css-analyzer#349]
Count the numbers and occasions where a shorthand directly overwrites a longhand, like so:

```css
element {
  font-size: 100%;
  font: inherit;
}
```

Maybe also look at identifying things like an immediate override within the same block, like so:

```css
element {
  color: red;
  color: blue;
}
```
