### ISSUE TITLE
calculate custom property complexity

### ISSUE THREAD

**Issue by bartveneman** [projectwallace/css-analyzer#385]
The web almanac uses custom property depth to calculate its complexity https://almanac.httparchive.org/en/2022/css#complexity

```css
:root {
  --base-hue: 335; /* depth = 0 */
  --base-color: hsl(var(--base-hue) 90% 50%); /* depth = 1 */
  --background: linear-gradient(var(--base-color), black); /* depth = 2 */
}
```
